application:
  title: BY CADN
  version: 1.0.0
server:
  address: 0.0.0.0
  port: 443
  ssl:
    key-store: C:/Users/cadn/Documents/GitHub/cadn_java_spring_boot_security/keystore.p12
    key-store-password: 31072001
    keyStoreType: PKCS12
    keyAlias: tomcat
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format-sql: true
#        generate-statistics: true
#      show-sql: true
  main:
    web-development-type: servlet

#logging:
#  level:
#    org:
#      hibernate:
#        type: trace
spring:
#  jpa:
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true

#  jackson:
#    deserialization:
#      fail-on-unknown-properties: false
#  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: 123456
#    driver-class-name: org.postgresql.Driver
  application:
    name: Application
#  security:
#    jwt:
#      secret-key: 9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d9
#      expiration-time: 64800000
#      refresh-token-expiration-time: 604800000
#  kafka:
#    bootstrap-servers: localhost:9092
#    admin:
#      client-id: kafka-admin
#    consumer:
#      auto-offset-reset: latest